import FormInputFieldsToezichtBestuursorgaanSelectEditComponent from "./edit";

export default class FormInputFieldsToezichtBestuursorgaanSelectShowComponent extends FormInputFieldsToezichtBestuursorgaanSelectEditComponent {

}
